name: CI

on: [workflow_dispatch]

jobs:
  lams_job:
    runs-on: ubuntu-latest
    name: LAMS LookML Linter Job
    steps:
    - name: Checkout your LookML
      uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
    - name: Install LAMS
      run: npm install -g @looker/look-at-me-sideways@5
    - name: Run LAMS
      # See [PRIVACY.md](https://github.com/looker-open-source/look-at-me-sideways/blob/master/PRIVACY.md)
      # output=github-job-summary is available as of LAMS v5. Older versions can use output=lines
      run: lams --reporting=save-yes --output=github-job-summary
